# Template: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
# Build On Multiple Platform
name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows
            arch: x86_64
            plat: windows
            xmake-arch: x64
            runs-on: windows-latest

          - os: ubuntu
            arch: x86_64
            plat: linux
            xmake-arch: x86_64
            runs-on: ubuntu-latest

          - os: ubuntu
            arch: arm64
            plat: linux
            xmake-arch: arm64
            runs-on: ubuntu-24.04-arm

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup XMake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Configure XMake
      run: xmake f -m release -p ${{ matrix.plat }} -a ${{ matrix.xmake-arch }}

    - name: Build Targets
      working-directory: ${{github.workspace}}
      run: xmake build
